In [194]:
import numpy as np
my_list = [1,2,3,4]
type(np.array(my_list))
arr = np.array(my_list)
type(arr)

#conversion of list into array



numpy.ndarray

In [195]:

b = np.array([[1,2,4],[2,5,6,8],[1,4]])
b.reshape(3,1)


array([[[1, 2, 4]],
       [[2, 5, 6, 8]],
       [[1, 4]]], dtype=object)

In [196]:
a = np.array([1,6,8,4,2,6,9,7,5,81,3,1], dtype=complex)
a

array([  1.+0.j,   6.+0.j,   8.+0.j,   4.+0.j,   2.+0.j,   6.+0.j,
         9.+0.j,   7.+0.j,   5.+0.j,  81.+0.j,   3.+0.j,   1.+0.j])

In [197]:
np.arange(-20,10,3)# array with steps

array([-20, -17, -14, -11,  -8,  -5,  -2,   1,   4,   7])

In [198]:
np.zeros((3,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [199]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [200]:
np.random.randint()#random number generator

TypeError: randint() takes at least 1 positional argument (0 given)

In [202]:
np.random.randint(0,1000,(4,4))

array([[490,  40, 502, 420],
       [371, 528, 356, 239],
       [395,  54, 344, 363],
       [122, 574, 545, 200]])

In [201]:
np.random.seed(10)#fix the random number 

arr =np.random.randint(0,100,10)
arr

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0])

In [193]:
np.random.seed(10)#fix the random number 

arr =np.random.randint(0,100,10)
arr.max()
arr.min()
arr.mean()
arr.argmax()
arr.argmin()
arr.reshape(2,5)

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [213]:
mat = np.arange(0,100).reshape(10,10)
print mat.flags()

SyntaxError: invalid syntax (<ipython-input-213-20e471faf701>, line 2)

In [204]:
mat[9,8]
mat[0,:]# for zeroth row and all colums
mat[1,0]# for zeroth coloums and all rows
mat[0:3,0:4]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [214]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print x.flags

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-214-be3971e98a99>, line 3)